jwt:
    issuer: chopoo2001@gmail.com
    secret: fZknx4Od2cDciVjZ4ywfjcbon2CBqMLu
logging:
    file:
        name: log/Sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate: info
            springframework:
                security: info
        root: info
server:
    servlet:
        context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234qweR!
        url: jdbc:mysql://13.125.249.38/Jboard
        username: jboard
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        # prefix 설정을 안하면 HTML 수정 후 브라우저에서 새로고침 반영안됨
        # 그리고 반드시 classpath로 쓰고 templates 마지막에(/) 붙이면 안됨(mapping 경로에 /경로1/경로1일 경우, 만약 경로1/경로2 이면 (/)붙여야함)
        prefix: classpath:/templates

    # 파일 첨부 설정 확인
    servlet:
        multipart:
            location: src/main/resources/static/file #경로
            max-file-size: 10MB #크기
